version: '3'
services:
  backend:
    image: malikumair096/mern-stack-mini-project-backend:latest
    ports:
      - "3001:3001"
  frontend:
    image: malikumair096/mern-stack-mini-project-frontend:latest
    ports:
      - "3000:3000"
